# Generated by Django 3.2 on 2021-05-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='description',
            field=models.CharField(default='Add Description', max_length=1000, verbose_name='Descripción'),
        ),
    ]
